### ISSUE TITLE
Alive/dead voice chat you can hear yourself

### ISSUE THREAD

**Issue by mzegar** [TTTReborn/tttreborn#161]
Get multiple users to connect to a game, use voice chat `+iv_voice` and make sure to produce a sound (i.e use your mic), you'll be able to hear yourself. Another user pops up in the UI, but you hear yourself.

There might be extra details on how to repo this bug, which are unknown at the moment.

**Comment by AMastryukov** [comment]
I knew I wasn't crazy. I've had this happen to me when we did the mini playtest some time ago.

**Comment by mzegar** [comment]
Potentially missing a check to make sure we aren't adding the current player to the list of players we should be hearing

`TTTPlayer.VoiceChat.cs` line `84`
