### ISSUE TITLE
`var == null` vs `var is null`

### ISSUE THREAD

**Issue by Alf21** [TTTReborn/tttreborn#192]
I saw you used `is null` earlier, we should probably just stick to one version unless there is some underlying difference. (which doesn't seem to be the case based on a quick google search)

I think we mostly do `== null` or `!= null` is our codebase, but I could be wrong.

_Originally posted by @mzegar in https://github.com/TTTReborn/tttreborn/pull/189#discussion_r689144058_

**Comment by mzegar** [comment]
I had the same idea haha, I'll close the other issue https://github.com/TTTReborn/tttreborn/issues/191

**Comment by Fires1** [comment]
`is` should be reserved for type checking `is Entity`...`is TTTxxxx`

Null checks should always be `== null` or with null coalescing.

**Comment by mzegar** [comment]
If someone wants to take this on as a first issue, we should use `== null` whenever checking if something is null. We should use `is` for type checking.
