### ISSUE TITLE
User Interface Rework & Unification

### ISSUE THREAD

**Issue by AMastryukov** [TTTReborn/tttreborn#195]
When interface elements are overlayed or when they are displayed over other things, their transparency causes some issues with visibility. The C4 Controls below show how obstructed the controls look when the player is interacting with the C4 Entity:
![image](https://user-images.githubusercontent.com/12959805/129762806-aea7963b-7ae9-4a45-bae9-38d5a2c845ee.png)

Additionally, creating new interface elements is a pain because there is no basic stylesheet from which to inherit and base your work from. As a result, there is a ton of code and stylesheet duplication and inconsistencies in the look and feel.

We need to rework the interface and unify the existing elements under the new system.

**Comment by AMastryukov** [comment]
- [ ] Design a set of generic user interface elements 
- [ ] Implement new elements
- [ ] Replace all existing elements with new elements

**Comment by mzegar** [comment]
@AMastryukov do we want to close this now?
