### ISSUE TITLE
When shooting 1 time, 2 shots are triggered

### ISSUE THREAD

**Issue by Alf21** [TTTReborn/tttreborn#202]
## Prerequisites

- [x] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary
As the title says. Could be caused by the prediction changes some days ago made by s&box.

## Expected behavior
Just 1 shot triggered.

**Comment by Krzyska-Filip** [comment]
There is a new devlog which explain it.
