### ISSUE TITLE
No weapons on round start

### ISSUE THREAD

**Issue by Alf21** [TTTReborn/tttreborn#203]
## Prerequisites

- [x] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary
Some players (most of all, connected players (not the hoster)) do not receive the start weapons not can pick dropped weapons up in some cases.

## Steps to reproduce
Unknown

**Comment by mzegar** [comment]
This still occurs, I managed to repro it while using `net_fakelag 200` before starting a server. I was trying to look into this bug https://github.com/TTTReborn/tttreborn/issues/332

**Comment by mzegar** [comment]
Steps to repo...

1. Launch up one client with net_fakelag 200 and sv_lan 1
2. Join the server using `connect localhost`
3. Play through rounds, notice that sometimes the RPC does not update the inventory.

The RPC is given a null carriable item so it ends up not updating the inventory. Still looking into ways to fix this.
