### ISSUE TITLE
Hammer-spawned weapon and ammo entities do not respawn when round restarts

### ISSUE THREAD

**Issue by Fires1** [TTTReborn/tttreborn#207]
## Prerequisites

- [x] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary

If you create a map and place down any TTTWeapon or TTTAmmo derivative, they will not respawn once the round is restarted. They just get deleted during cleanup.

Ideally, these locations need to be cached once the map has been loaded, so they can be deleted and then respawned.
My proposed solution would be to expand on TTTMapSettings (once map-entities is merged) and have `Game` store a `MapSettings` struct that contains relevant content (such as custom player models or clothing), as well as lists for all locations of TTTAmmoRandom, TTTWeaponRandom and all ammo/weapons that spawn in by default.
This problem does not occur with the random entities as they do not get deleted, Preround calls `Activate` on them, which spawns a random TTTAmmo or TTTWeapon derivative.

## Expected behavior

They respawn.

## Actual behavior

They don't.

## Steps to reproduce

Create a map with those entities (such as ttt_smg and ttt_ammo_smg) and they will not respawn.

**Comment by Alf21** [comment]
Afaik, you can check `IsFromMap` after `PostLevelLoaded` to populate a Dictionary with { key: WeaponType, value: Vector3Position}.
