### ISSUE TITLE
UI HUD Child Overlapping Issue

### ISSUE THREAD

**Issue by GravityWolfNotAmused** [TTTReborn/tttreborn#228]
## Prerequisites
Observe which HudPanel is last added to the Hud class.

## Summary
After the changes that were made in #212 to the hud, there has been an issue with interacting with the first child added.

In #212, we had moved all of the children from the parent of the hud to the parent of the hud panel (AliveHud, and GeneralHud), so we could toggle off the alive hud in an easier manner. This is likely due to us drawing two full-screen panels on top of one another.

## Steps to reproduce
Interact with Menu.Menu(Settings Menu) if GeneralHud is drawn last, or QuickShop if it's drawn first.

## Expected behavior
I should be able to interact with all menus regardless if they are in AliveHud or GeneralHud.

## Actual behavior
I can only interact with the last child added.

- [x] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

**Comment by mzegar** [comment]
FIXED https://github.com/TTTReborn/tttreborn/commit/9268535d76d61f999ac427f0dd9590a3bba0e099
