### ISSUE TITLE
Disable F1 Dev Menu

### ISSUE THREAD

**Issue by mzegar** [TTTReborn/tttreborn#264]
## Prerequisites

- [X] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary

Players can use the F1 (dev menu) ingame.

## Expected behavior

We should only let admins use this menu probably, or disable it entirely.

**Comment by Alf21** [comment]
I'd delay implementing this for a long time in order being able to receive error reports from non-admins as well :)

**Comment by mzegar** [comment]
Closing any issues I created since I am not a part of the project, please feel free to reopen any issues. (I don't want to be pinged relating any status updates)
