### ISSUE TITLE
Debug Mode stopped working

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [TTTReborn/tttreborn#327]
## Prerequisites

- [x] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary
Enabling debug mode won't work anymore and just straight to the next run.

## Expected behavior
Should stop the round from ending

## Actual behavior
Next round starts immediately after preparing

## Steps to reproduce
> Set min players to 1
> Enable Debug Mode

**Comment by mzegar** [comment]
Thanks, should be able to fix this soon. If you want, you can just use `bot_add` or `bot_add_dummy` with `min_players` set to 2, and the round shouldn't end.

**Comment by mzegar** [comment]
Hi, so just to confirm, the repo steps would be...

1. Set `min_players` to `1`
2. Enable `Suppress victory`
3. The round timer does not pause and goes into the next round?

I tested this on master and I'm able to sit in the `IN PROGRESS` round forever by myself.

@Alf21 However, if I open up the menu again, navigate to server and debug, the setting seems to turn off and reset even though it's enabled. Related to #323 ?

**Comment by Alf21** [comment]
Is it fixed with the latest PR? I found a bug with the switch settings which seem to be introduced within some sbox update (change)
