### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [TTTReborn/tttreborn#331]
## Summary
When changing settings they don't save.

## Expected behavior
The settings should save

## Actual behavior
The settings don't save

## Steps to reproduce
Change a setting,
Close the menu,
Open the menu again,
Settings are the same as before you changed them.

File save and load doesn't work either.

**Comment by mzegar** [comment]
Thanks for the issue, @Alf21 basically what I tagged you here with https://github.com/TTTReborn/tttreborn/issues/327#issuecomment-962738702
