### ISSUE TITLE
Thrown weapons are added to inventory

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [TTTReborn/tttreborn#332]
## Prerequisites

- [X ] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary
Picked up weapons thrown by hands are added to your inventory, allowing you to have multiple primary weapons

## Expected behavior
When you pick up a weapon and throw it, it shouldn't be added to your inventory

## Actual behavior
When you throw it, it adds two of the same kind to your inventory, despite already owning a primary weapon.

## Steps to reproduce
>Use hands to pick up a weapon
>Throw it
![image](https://user-images.githubusercontent.com/93285193/141180879-9a811605-7499-4164-8d53-b33ebae743a3.png)

**Comment by mzegar** [comment]
Hi, I'm unable to repo.

1. Have a shotgun in your inventory
2. Pickup a shotgun using hands
3. Throw or drop the weapon

It seems to work fine on my end.

![image](https://user-images.githubusercontent.com/32153021/141216448-b3436bb1-ac16-4acf-a05a-5434cb36ba24.png)
![image](https://user-images.githubusercontent.com/32153021/141216462-8d4a94ac-881e-495b-a040-f0f2b65ac34c.png)

**Comment by mzegar** [comment]
We have a new `use` system, I don't think this should occur anymore. Open this ticket up again if it does. Thanks!
