### ISSUE TITLE
Overhaul TTT Menu

### ISSUE THREAD

**Issue by mzegar** [TTTReborn/tttreborn#339]
## Prerequisites

- [X] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary

I'm open to having a discussion about this, but I think we should overhaul the TTT Menu which contains all the server settings, etc. 

1. Let's just copy over all of the UI components that come with the game, i.e radio menus, color pickers, etc. There isn't any reason to reinvent the wheel `\base\code\UI` contains these. I'm assuming they are pretty well implemented and are pretty customizable (styling-wise). 
2. I think we should remove the ability to resize the window, are there any use cases where a player will open the TTT menu and resize it? This includes the ability to drag the window about as well. 
3. We will want to split up every single UI content page to it's own class and seperate file, currently we have a `Menu.cs` & `Menu.scss` god class

I'm happy to take on this initiative and create a new UI panel that'll phase out the old one. Thoughts, @Alf21

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
Using the base game UI sounds like a cool idea to me, doesn't only look good but is nice to interact with.
The current menu looks good too but is unreliable for me most of the time.

**Comment by mzegar** [comment]
Yeah, there are definitely some bugs with it, Alf wrote it during this weird time where there wasn't certain UI functionality available in s&box, etc. etc. I'm sure he could re-iterate on it and fix everything, but, I think it probably makes sense to just snatch s&box defaults.

**Comment by mzegar** [comment]
https://github.com/TTTReborn/tttreborn/pull/368

**Comment by mzegar** [comment]
Done in #368 :)
