### ISSUE TITLE
Detect when a new round begins in Hammer

### ISSUE THREAD

**Issue by mzegar** [TTTReborn/tttreborn#348]
## Prerequisites

- [X] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

Add a way in Hammer to detect when a new set of rounds have started (i.e when the Preparing round has started)

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
This already exists through the ttt_map_settings entity

**Comment by mzegar** [comment]
@Hochgeschwindigkeitsrennfahrer thanks!
