### ISSUE TITLE
ent_path_platform (moving objects) don't reset after round change

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [TTTReborn/tttreborn#359]
## Prerequisites

- [x] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary
ent_path_platform, which is used for moving objects on a dedicated path (e.g. the lego helicopter), fails to reset after round end.
 
## Expected behavior
It should be on it's initial position on each round start

## Actual behavior
Once moved, it will stay on it's last position throughout the rounds.

## Steps to reproduce
Go on TTT Lego, inside the T room activate the board button to crash the heli and ambulance, see it's not resetting after round end.

**Comment by mzegar** [comment]
We may need to make an issue on s&box, `PathPlatformEntity` doesn't seem to have anything to reset the path platform. I also attempted deleting and recreating the entity but had no luck.

**Comment by mzegar** [comment]
Waiting on this https://github.com/Facepunch/sbox-issues/issues/1475

**Comment by mzegar** [comment]
Slightly fixed with latest changes, the ents are properly reset to first node, waiting on final response.
