### ISSUE TITLE
Flashlight

### ISSUE THREAD

**Issue by AMastryukov** [TTTReborn/tttreborn#62]
The flashlight should be available to players at all times regardless of whether they are holding a weapon or not, and should point at where the player is looking.

Known Issues:
- Deleting a Flashlight entity doesn't seem to work (maybe has to be a server call?)
- If not attaching to a bone (i.e. weapon muzzle) and setting position every frame, the flashlight position appears to stutter

**Comment by Alf21** [comment]
Fixed with #97
