### ISSUE TITLE
Decide Coding Style

### ISSUE THREAD

**Issue by AMastryukov** [TTTReborn/tttreborn#65]
- [x] Discuss with team and decide which coding style to go with
- [x] Format existing codebase with decided codeing style

**Comment by mzegar** [comment]
This has mostly been done. We've done mass PRs that fix up some of the coding style, and we have our `.editorconfig` file.

**Comment by GravityWolfNotAmused** [comment]
@mzegar I can work on that, I already worked through most of the non-UI code, I just didn't want to go around creating merge conflicts, but I guess those can be easily fixed.

**Comment by mzegar** [comment]
Yeah I feel like we have enough of our code base converted to our `.editorconfig` style, as PRs come along we can convert more.
