### ISSUE TITLE
Spectator Camera

### ISSUE THREAD

**Issue by AMastryukov** [TTTReborn/tttreborn#66]
Add multiple spectator camera types:

- [x] First-person spectator camera (shows player's perspective)
- [x] Third-person spectator camera (allows camera rotation centered around a specific player)
- [x] Free-style spectator camera (allows flying around using WASD keys)

**Comment by mzegar** [comment]
https://github.com/TTTReborn/tttreborn/pull/116
Adds free spectator camera + third person spectator, first-person still needs to be done. Consider checking out the s&box discord on how implementation should go, but, from what I remember we'll need to create the viewmodels again on the spectating client.
